config/routes.rb
Rails.application.routes.draw do
  get '/' => "chains#landing", as: "root"
  get '/chains/map' => "chains#map", as: 'map'

  resources :chains do
    resources :userposts
  end 
end

app/models/chain.rb
class Chain < ActiveRecord::Base
	has_many :userposts
end

app/models/userpost.rb
class Userpost < ActiveRecord::Base
	belongs_to :chain
	  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
	def index
		@chains = Chain.all
		@chain = Chain.find 1
		@user_posts = @chain.userposts
	end

	def show
		@chain = Chain.find params[:id]	

	end

	def landing

		
	end


end

app/controllers/userposts_controller.rb
class UserpostsController < ApplicationController
	def index
		@chain = Chain.find(params[:chain_id])
		@userposts = @chain.userposts
	end

	def create	
		comment = params[:comment]
		user = params[:user]
		address = params[:city]

		chain = Chain.find(params[:chain_id])
		chain.userposts.create comment: comment, user: user, address: address

		render json: 1
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chains_helper.rb
module ChainsHelper
end

app/helpers/userposts_helper.rb
module UserpostsHelper
end

app/views/chains/index.html.erb
<% @chains.each do |chain| %><br>

	<div class="chain-container container col-md-10 col-md-offset-1" id="chain<%=chain.id%>" name="<%=chain.id%>"><%= chain.name %></div>

	<% chain.userposts.each do |userpost| %>
		<div class="container">
		    <ul class="timeline">
		        <li>
		          <div class="timeline-badge up"><i class="fa fa-thumbs-up"></i></div>
			          <div class="timeline-panel">
			            <div class="timeline-heading">
			              <h4 class="timeline-title">User: <%= userpost.user %></h4>
			            </div>
			            <div class="timeline-body">
			              <p>Comment: <%= userpost.comment %></p>
			              <p>City: <%= userpost.address %></p>
			            </div>
			          </div>
			      </div>
		        </li>
		    </ul>
		</div>
	<% end %>		

	<div class="form-container">
		<%= text_field_tag :user, nil, id: nil, name: chain.id, class: "user-field", :placeholder => "Name", size: 40 %><br>
		<%= text_area_tag :comment, nil, id: nil, name: chain.id, class: "comment-field", :placeholder => "Put here your experience", size: '30x3' %><br>
		<%= text_field_tag :address, nil, id: nil, name: chain.id, class: "city-field", :placeholder => "City", size: 40 %><br>
		
		<button class="btn-send" name="<%=chain.id %>" >Send!</button>
	</div>

<%end%>

<div class="new-chain">
<button class="btn-chain">Create a new chain</button>
</div>

app/views/chains/map.html.erb
<div id="map-canvas" style="width: 765px; height: 388px"></div>

app/views/chains/show.html.erb
 <%= @chain.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PROYECTO</title>
	  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		
	  
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	 
	  <%= csrf_meta_tags %>
	  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

	  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	</head>
	<body>
		<header>
			FAVOROOTS 
			<span class="btn-group-pull-right">
	            <%= link_to'Info' %>
	            <%= link_to 'Chains', chains_path %>
	            <%= link_to 'Map', map_path %>
	 	</span>
		</header>
		<img class= "background_image" src="/fondo.jpg">

	
		<%= yield %>

<script src="http://maps.googleapis.com/maps/api/js"></script>
 <%= javascript_include_tag 'application' %>
		<footer> 
			<hr> Created by Irene Muñoz Real ® Ironhack 2015

		</footer>
	</body>
</html>

app/views/userposts/new.html.erb
new.html.erb